# NOTE: `jekyll serve --watch` doesn't watch this file!
# The excludes don't get served at all.
exclude:  ['README.md', 'Makefile', 'assets/less', 'assets/vendor/bootstrap', 'indexTemplate.md']
# The hides get served but are hidden in the site tree.
# NOTE: They require a leading /
hide: ['/sitemap.xml', '/sitePages.json', '/robots.txt', '/example.html', '/functions.js', '/foobar.exe']
timezone: America/Los_Angeles
markdown: kramdown
kramdown:
  toc_levels: "1,2,3,4,5"
plugins:
  - jekyll-sitemap
  - jemoji
